// <auto-generated />
using System;
using Flighter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flighter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311110300_useradminrelation")]
    partial class useradminrelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flighter.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.BookingModel", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("bookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("paymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ticketId")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("ticketId");

                    b.HasIndex("userId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.ClassTypeModel", b =>
                {
                    b.Property<int>("classTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("classTypeId"));

                    b.Property<string>("className")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("classTypeId");

                    b.ToTable("classTypes");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.CompanyModel", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightModel", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("FlightTypeId")
                        .HasColumnType("int");

                    b.Property<string>("fromLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightId");

                    b.HasIndex("FlightTypeId");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightSeatModel", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("SeatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.Property<bool>("isBooked")
                        .HasColumnType("bit");

                    b.Property<int>("ticketId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("flightId");

                    b.HasIndex("ticketId");

                    b.ToTable("Flightseats");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightTypeModel", b =>
                {
                    b.Property<int>("FlightTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightTypeId"));

                    b.Property<string>("FlightName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightTypeId");

                    b.ToTable("FlightTypes");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.PaymentModel", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("bookingId")
                        .HasColumnType("int");

                    b.Property<string>("cardHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("userId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.ScheduleModel", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateOnly>("arrivalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("arrivalTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("returnDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("returnTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("flightId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.TicketModel", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("availableSeats")
                        .HasColumnType("int");

                    b.Property<int>("classTypeId")
                        .HasColumnType("int");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.Property<string>("flightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isOffer")
                        .HasColumnType("bit");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("scheduleId")
                        .HasColumnType("int");

                    b.Property<int>("totalSeats")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TicketId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("classTypeId");

                    b.HasIndex("flightId");

                    b.HasIndex("scheduleId");

                    b.HasIndex("userId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "b1719902-b611-427a-8233-3c9025a72677",
                            ConcurrencyStamp = "6a9fb18d-6413-47c9-8eb8-19563b23bbf6",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = "3be15aff-8c51-4bcf-a3ff-37f6f1678f0b",
                            ConcurrencyStamp = "a2f2b045-736d-4f6d-9617-c0e2a86b44ae",
                            Name = "Company",
                            NormalizedName = "COMPANY"
                        },
                        new
                        {
                            Id = "a984a9e5-4d98-4ea9-b3fd-a6b960c19412",
                            ConcurrencyStamp = "7b524207-7c63-46f6-83a8-cf1dcf2e88d6",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Flighter.Models.ApplicationUser", b =>
                {
                    b.HasOne("Flighter.Models.DBModels.CompanyModel", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Flighter.DTO.RefreshTokens", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicationUserId", "Id");

                            b1.ToTable("RefreshTokens");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });

                    b.Navigation("Company");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.BookingModel", b =>
                {
                    b.HasOne("Flighter.Models.DBModels.PaymentModel", "payment")
                        .WithMany("bookings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.DBModels.TicketModel", "ticket")
                        .WithMany("bookings")
                        .HasForeignKey("ticketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.ApplicationUser", "user")
                        .WithMany("bookings")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("payment");

                    b.Navigation("ticket");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightModel", b =>
                {
                    b.HasOne("Flighter.Models.DBModels.FlightTypeModel", "FlightType")
                        .WithMany("Flights")
                        .HasForeignKey("FlightTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FlightType");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightSeatModel", b =>
                {
                    b.HasOne("Flighter.Models.DBModels.FlightModel", "flight")
                        .WithMany("seats")
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.DBModels.TicketModel", "ticket")
                        .WithMany("seats")
                        .HasForeignKey("ticketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("flight");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.PaymentModel", b =>
                {
                    b.HasOne("Flighter.Models.ApplicationUser", "user")
                        .WithMany("payments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.ScheduleModel", b =>
                {
                    b.HasOne("Flighter.Models.DBModels.FlightModel", "flight")
                        .WithMany("schedules")
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.TicketModel", b =>
                {
                    b.HasOne("Flighter.Models.DBModels.CompanyModel", "Company")
                        .WithMany("Tickets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.DBModels.ClassTypeModel", "classType")
                        .WithMany("tickets")
                        .HasForeignKey("classTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.DBModels.FlightModel", "flight")
                        .WithMany("tickets")
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.DBModels.ScheduleModel", "schedule")
                        .WithMany("tickets")
                        .HasForeignKey("scheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flighter.Models.ApplicationUser", "Admin")
                        .WithMany("tickets")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("classType");

                    b.Navigation("flight");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("Flighter.Models.ApplicationUser", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("payments");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.ClassTypeModel", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.CompanyModel", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightModel", b =>
                {
                    b.Navigation("schedules");

                    b.Navigation("seats");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.FlightTypeModel", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.PaymentModel", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.ScheduleModel", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Flighter.Models.DBModels.TicketModel", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("seats");
                });
#pragma warning restore 612, 618
        }
    }
}
